import type { WindZone } from '@/types';

export const APP_NAME = 'PermitPro FL';
export const APP_VERSION = '0.1.0';

export const WIND_ZONE_MAP: Record<string, WindZone> = {
  'alachua': 'II',
  'baker': 'II',
  'bay': 'III',
  'bradford': 'II',
  'brevard': 'III',
  'broward': 'III',
  'calhoun': 'II',
  'charlotte': 'III',
  'citrus': 'II',
  'clay': 'II',
  'collier': 'III',
  'columbia': 'II',
  'desoto': 'II',
  'dixie': 'II',
  'duval': 'II',
  'escambia': 'III',
  'flagler': 'II',
  'franklin': 'III',
  'gadsden': 'II',
  'gilchrist': 'II',
  'glades': 'II',
  'gulf': 'III',
  'hamilton': 'II',
  'hardee': 'II',
  'hendry': 'II',
  'hernando': 'II',
  'highlands': 'II',
  'hillsborough': 'II',
  'holmes': 'II',
  'indian-river': 'III',
  'jackson': 'II',
  'jefferson': 'II',
  'lafayette': 'II',
  'lake': 'II',
  'lee': 'III',
  'leon': 'II',
  'levy': 'II',
  'liberty': 'II',
  'madison': 'II',
  'manatee': 'III',
  'marion': 'II',
  'martin': 'III',
  'miami-dade': 'III',
  'monroe': 'III',
  'nassau': 'II',
  'okaloosa': 'III',
  'okeechobee': 'II',
  'orange': 'II',
  'osceola': 'II',
  'palm-beach': 'III',
  'pasco': 'II',
  'pinellas': 'III',
  'polk': 'II',
  'putnam': 'II',
  'santa-rosa': 'III',
  'sarasota': 'III',
  'seminole': 'II',
  'st-johns': 'II',
  'st-lucie': 'III',
  'sumter': 'II',
  'suwannee': 'II',
  'taylor': 'II',
  'union': 'II',
  'volusia': 'II',
  'wakulla': 'III',
  'walton': 'III',
  'washington': 'II',
};

export const PERMIT_STATUSES = [
  { value: 'draft', label: 'Draft', color: 'gray' },
  { value: 'in-progress', label: 'In Progress', color: 'blue' },
  { value: 'review', label: 'Under Review', color: 'yellow' },
  { value: 'submitted', label: 'Submitted', color: 'purple' },
  { value: 'approved', label: 'Approved', color: 'green' },
  { value: 'rejected', label: 'Rejected', color: 'red' },
] as const;

export const DOCUMENT_TYPES = [
  { value: 'site-plan', label: 'Site Plan' },
  { value: 'blocking-chart', label: 'Blocking/Anchor Chart' },
  { value: 'deed', label: 'Deed' },
  { value: 'data-plate', label: 'Data Plate' },
  { value: 'elevation-cert', label: 'Elevation Certificate' },
  { value: 'noc', label: 'Notice of Commencement' },
  { value: 'floor-plan', label: 'Floor Plan' },
  { value: 'other', label: 'Other' },
  { value: 'signed-pdf', label: 'Signed PDF' },
] as const;

export const DEFAULT_FEES = {
  salesTaxRate: 6.0,
  permitFee: 0,
  impactFee: 0,
  planReviewFee: 0,
};

export const FL_STATES_DROPDOWN = ['FL'] as const;
